# Generated by Django 2.0.13 on 2019-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_application_period',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_howto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_qna',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_reward',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_who_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_uniqueness',
            field=models.TextField(blank=True),
        ),
    ]
