# Generated by Django 2.0.13 on 2019-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_auto_20190605_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_completion_semester',
            field=models.PositiveSmallIntegerField(choices=[(0, '아직 수료하지 않았습니다.'), (1, '1학기'), (2, '2학기'), (3, '3학기'), (4, '4학기'), (5, '5학기'), (6, '6학기'), (7, '7학기'), (8, '8학기')], default=8, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_grade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_income_level',
            field=models.PositiveSmallIntegerField(choices=[(0, '0분위'), (1, '1분위'), (2, '2분위'), (3, '3분위'), (4, '4분위'), (5, '5분위'), (6, '6분위'), (7, '7분위'), (8, '8분위'), (9, '9분위'), (10, '10분위')], default=10, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_living_area',
            field=models.CharField(choices=[('KEYNGIDO', '경기도'), ('SEOUL', '서울특별시'), ('BUSAN', '부산'), ('DAEGOO', '대구'), ('INCHEON', '인천'), ('DAEJUN', '대전'), ('ULSAN', '울산'), ('KANGWONDO', '강원도'), ('CHUNGCHUNGBOOKDO', '충청북도'), ('CHUNGCHUNGNAMDO', '충청남도'), ('JEOLABOOKDO', '전라북도'), ('JEOLANAMDO', '전라남도'), ('KEYONGSANGBOOKDO', '경상북도'), ('KEYONGSANGNAMDO', '경상남도'), ('SEJONG', '세종특별자치시'), ('JEJUDO', '제주도')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_uniqueness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
