# Generated by Django 2.0.13 on 2019-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_auto_20190606_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_grade',
            field=models.FloatField(null=True),
        ),
    ]
