# Generated by Django 2.0.13 on 2019-06-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auto_20190606_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_completion_semester',
            field=models.PositiveSmallIntegerField(choices=[(0, '아직 수료하지 않았습니다.'), (1, '1학기'), (2, '2학기'), (3, '3학기'), (4, '4학기'), (5, '5학기'), (6, '6학기'), (7, '7학기'), (8, '8학기')], default=10),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_grade',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.Scholar_content'),
        ),
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_living_area',
            field=models.CharField(choices=[('KEYNGIDO', '경기도'), ('SEOUL', '서울특별시'), ('BUSAN', '부산'), ('DAEGOO', '대구'), ('INCHEON', '인천'), ('DAEJUN', '대전'), ('ULSAN', '울산'), ('KANGWONDO', '강원도'), ('CHUNGCHUNGBOOKDO', '충청북도'), ('CHUNGCHUNGNAMDO', '충청남도'), ('JEOLABOOKDO', '전라북도'), ('JEOLANAMDO', '전라남도'), ('KEYONGSANGBOOKDO', '경상북도'), ('KEYONGSANGNAMDO', '경상남도'), ('SEJONG', '세종특별자치시'), ('JEJUDO', '제주도')], default=None, max_length=200, null=True),
        ),
    ]
