# Generated by Django 2.0.13 on 2019-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20190607_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueness',
            name='u_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.Scholar_content'),
        ),
    ]
