# Generated by Django 2.0.13 on 2019-06-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_auto_20190607_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_fliter',
            name='filter_completion_semester',
            field=models.PositiveSmallIntegerField(choices=[(0, '아직 수료하지 않았습니다.'), (1, '1학기'), (2, '2학기'), (3, '3학기'), (4, '4학기'), (5, '5학기'), (6, '6학기'), (7, '7학기'), (8, '8학기')], default=0),
        ),
    ]
