# Generated by Django 2.0.13 on 2019-06-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20190607_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar_content',
            name='scholar_application_period',
        ),
        migrations.AddField(
            model_name='scholar_content',
            name='scholar_application_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholar_content',
            name='scholar_application_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.Scholar_filter'),
        ),
    ]
