# Generated by Django 2.0.13 on 2019-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_auto_20190608_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_filter',
            name='scholar_application_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
