# Generated by Django 2.0.13 on 2019-06-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_auto_20190610_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar_content',
            name='form_file',
            field=models.FileField(null=True, upload_to='', verbose_name='양식업로드'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_application_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제출기간 마지막'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_application_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제출기간 시작'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_foundation_name',
            field=models.CharField(max_length=200, verbose_name='장학재단이름'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_howto',
            field=models.TextField(blank=True, verbose_name='접수방법'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='장학이름'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_needs',
            field=models.TextField(blank=True, verbose_name='제출서류'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_qna',
            field=models.TextField(blank=True, verbose_name='장학문의번호'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_recruitment_num',
            field=models.PositiveIntegerField(verbose_name='선발인원'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_reward',
            field=models.TextField(blank=True, verbose_name='장학혜택'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='scholar_who_draft',
            field=models.TextField(blank=True, verbose_name='선발대상'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='garbage', max_length=100, verbose_name='슬러그'),
        ),
        migrations.AlterField(
            model_name='scholar_content',
            name='thumb_nail',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_completion_semester',
            field=models.PositiveSmallIntegerField(choices=[(0, '아직 수료하지 않았습니다.'), (1, '1학기'), (2, '2학기'), (3, '3학기'), (4, '4학기'), (5, '5학기'), (6, '6학기'), (7, '7학기'), (8, '8학기')], default=0, verbose_name='수료학기'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_grade',
            field=models.FloatField(default=0, verbose_name='성적'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.Scholar_content', verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_income_level',
            field=models.PositiveSmallIntegerField(choices=[(0, '0분위'), (1, '1분위'), (2, '2분위'), (3, '3분위'), (4, '4분위'), (5, '5분위'), (6, '6분위'), (7, '7분위'), (8, '8분위'), (9, '9분위'), (10, '10분위')], default=10, null=True, verbose_name='소득분위'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_is_our_college',
            field=models.BooleanField(default=False, verbose_name='교내/교외'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_living_area',
            field=models.CharField(choices=[('KEYNGIDO', '경기도'), ('SEOUL', '서울특별시'), ('BUSAN', '부산'), ('DAEGOO', '대구'), ('INCHEON', '인천'), ('DAEJUN', '대전'), ('ULSAN', '울산'), ('KANGWONDO', '강원도'), ('CHUNGCHUNGBOOKDO', '충청북도'), ('CHUNGCHUNGNAMDO', '충청남도'), ('JEOLABOOKDO', '전라북도'), ('JEOLANAMDO', '전라남도'), ('KEYONGSANGBOOKDO', '경상북도'), ('KEYONGSANGNAMDO', '경상남도'), ('SEJONG', '세종특별자치시'), ('JEJUDO', '제주도')], default=None, max_length=200, null=True, verbose_name='소재지'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='filter_uniqueness',
            field=models.TextField(blank=True, null=True, verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='scholar_filter',
            name='scholar_application_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='자동생성 제출기간 마지막'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_1',
            field=models.BooleanField(default=False, verbose_name='다문화가정'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_10',
            field=models.BooleanField(default=False, verbose_name='학생가장'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_11',
            field=models.BooleanField(default=False, verbose_name='농어촌자녀'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_2',
            field=models.BooleanField(default=False, verbose_name='기초생활수급자'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_3',
            field=models.BooleanField(default=False, verbose_name='차상위계층'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_4',
            field=models.BooleanField(default=False, verbose_name='장애인'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_5',
            field=models.BooleanField(default=False, verbose_name='새터민'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_6',
            field=models.BooleanField(default=False, verbose_name='보훈대상자'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_7',
            field=models.BooleanField(default=False, verbose_name='조부모가정'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_8',
            field=models.BooleanField(default=False, verbose_name='다자녀'),
        ),
        migrations.AlterField(
            model_name='uniqueness',
            name='u_9',
            field=models.BooleanField(default=False, verbose_name='한부모'),
        ),
    ]
