# Generated by Django 2.0.13 on 2019-06-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0003_auto_20190606_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruniqueness',
            name='u_ID',
        ),
        migrations.AddField(
            model_name='useruniqueness',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
