# Generated by Django 2.0.13 on 2019-06-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20190606_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruniqueness',
            old_name='user',
            new_name='u_ID',
        ),
    ]
